version: '3'

services:

  shop-frontend:
    
    build:
      context: .
      dockerfile: dockerfile
    container_name: benevolo-shop-frontend
    image: ghcr.io/thi24/shop-frontend:latest
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true
