version: '3'

services:

  shop-frontend:
    
    build:
      context: .
      dockerfile: dockerfile
    container_name: benevolo-shop-frontend
    image: ghcr.io/thi24/shop-frontend:latest
    ports:
      - "8080:3000"
