FROM node:20-slim AS base

ARG VITE_STRIPE_KEY
ARG VITE_API_BASE_URL
ARG VITE_AUTH_TOKEN
ENV VITE_STRIPE_KEY=$VITE_STRIPE_KEY
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_AUTH_TOKEN=$VITE_AUTH_TOKEN

# create destination directory
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app

# update and install dependency
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y git

# copy the app, note .dockerignore
COPY . /usr/src/nuxt-app/
RUN npm install
RUN npm run build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "npm", "start" ]